projects:
  app:
    schemaPath: "src/schema.gql"
    extensions:
      endpoints:
        default: "http://localhost:${env:PORT}/graphql"
  database:
    schemaPath: "src/generated/prisma.graphql"
    extensions:
      prisma: database/prisma.yml
